### PR TITLE
fix: event/accomplishment modal styles

### LINKED ISSUE #447: discard: remove double containers (card nested in discard confirm container)

### PR DESCRIPTION
**Pull request by Nick42791**
Accomplishment modals:
- just have the same data as the cards smaller version of the card. there are some cases where this could be useful, the times when the description is not on the small version of the card, but in many cases, it might feel unhelpful and redundant. Maybe we consider removing the info icon entirely, only rendering it when the description can not also fit.

Event Modals:
- have the same data as the card
- when a new event is generated, so is a modal, which brings them front and center, as previously discussed. On events where interaction is necessary, an 'Interact' button appears, which closes the modal. When interaction is not required, a 'Continue' button appears, which sets player readiness and closes the modal

close #447

### CODE REVIEW

**Comment by chrstngyn** [comment]
this is a good start. we should leave this PR up so we can further discuss how we want to refactor the cards after the pretest. also, since we're waiting to receive UI feedback from Will, that could also be helpful in refactoring the cards.

File: client/src/components/game/phases/events/EventCard.vue [hunk 1]
```diff
@@ -80,6 +94,28 @@ export default class EventCard extends Vue {
...
   }
 
+  private eventNoChangeViews: Array<EventClientView> = [
+    'NO_CHANGE',
+    'AUDIT',
+    'DISABLE_CHAT'
+  ];
+
+  get requiresInteraction() {
+    if(!this.eventNoChangeViews.includes(this.event.clientViewHandler)){
```
Comment (alee) [inline client/src/components/game/phases/events/EventCard.vue:104]: this could be simplified to 

`return !this.eventNoChangeViews.includes(this.event.clientViewHandler)`

File: client/src/api/tutorial/request.ts [hunk 2]
```diff
@@ -189,8 +189,10 @@ export class TutorialAPI  {
 
   //MODAL HANDLERS
   public setModalVisible(data: any){
-    this.store.commit('SET_MODAL_VISIBLE',data);
-    this.completedActionWithImplicitForward();
+    if(data.data.activator != 'Server'){
```
Comment (alee) [inline client/src/api/tutorial/request.ts:192]: This conditional check makes me a bit squirmy. I'm not sure what the right design is since I don't know what `data.data` is, or what activator means, etc.

Comment (Nick42791) [reply client/src/api/tutorial/request.ts:192]: Yeah, activator does mean that. With this implementation, a modal is generated every time an event comes in. This is fine in the game, and doesn't require any extra logic. In the Tutorial, we actually don't want that modal to appear, because it ruins the flow of everything else (we do the same thing with discard).

As for the data.data call, perhaps data:any should be renamed to modalInfo:ModalData, where ModalData is built of the modal types. (this may already be a thing @lfaivre, if you know, that would be great). Either way, the argument passed into the function has two attributes: type and data. Inside data, there is an activator attribute, which is just a string (Again, if @lfaivre hasn't done it already, we may look into defining a type for these values). 

This was just a quick way to prevent an undesired action in the Tutorial, but if you have any alternative suggestions, that would be great!
