### PR TITLE
fix: use plain http form for submitting website problems

### LINKED ISSUE #266: use plain http form for submitting website problems
A plain http form with a mailto form is simpler than submitting to the server. How about something like

https://stackoverflow.com/questions/12626940/mailto-on-submit-button

instead of sending to the server and having the server handle it? #241

### PR DESCRIPTION
**Pull request by lfaivre**
note:

* closes #266

### CODE REVIEW

**Comment by lfaivre** [comment]
using the mailto option is a little less predictable than the mail service, i had an issue with chrome being assigned as the default mail client, but should otherwise work fine

File: client/src/components/global/UserHeader.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
   <div class="user-header">
     <div class="problem">
-      <button @click="openModalProblem">[ <span>BETA</span> ] <span>Report a Problem</span></button>
+      <a href="mailto:sender@example.com?subject=New Issue Submission">[ <span>BETA</span> ] <span>Report a Problem</span></a>
```
Comment (alee) [inline client/src/components/global/UserHeader.vue]: `sender@example.com` should be a configurable email address pulled from somewhere (server-side settings @cpritcha?) or at least hard-coded to something like portmars@asu.edu for now.

Let's also change the subject to "[port-of-mars] issue" or something along those lines

Comment (cpritcha) [reply client/src/components/global/UserHeader.vue]: I think hard wiring to portmars@asu.edu in the form is fine for now because it only exists there for now. Eventually it would be good to put idea to create some shared settings

Comment (lfaivre) [reply client/src/components/global/UserHeader.vue]: fixed in newest commit
