### PR TITLE
fix: allow altruistic trades

### LINKED ISSUE #450: allow altruistic trade
in a trade request, allow player to request resources without offering up resources (0 for X>1 or X>1 for 0, but no 0 for 0)

### PR DESCRIPTION
**Pull request by lfaivre**
notes:

- closes #450

### CODE REVIEW

File: shared/src/validation.ts [hunk 1]
```diff
@@ -10,44 +20,46 @@ export function canPurchaseAccomplishment(accomplishment: AccomplishmentData, in
   return true;
 }
 
-
 //might move to TradeOptions.vue
 export function makeTradeSafe(resources: ResourceAmountData) {
   for (const resource of RESOURCES) {
-    if (typeof resources[resource] == "string") {
+    if (typeof resources[resource] == 'string') {
```
Comment (alee) [inline shared/src/validation.ts:26]: hmm, can we document what this is guarding against? also for consistency should this be an `===`?

Comment (lfaivre) [reply shared/src/validation.ts:26]: i wasn't sure either, but left it just in case it was needed. i believe @Nick42791 originally wrote it. i'd think typescript and the triple equivalency operator in its place would guard against any type issue created by passing in unwanted values for the resources

Comment (Nick42791) [reply shared/src/validation.ts:26]: Because you can't type the number in anymore, it's not necessary. 

It was needed when you could type the number in directly, because users could send blank data.

Comment (lfaivre) [reply shared/src/validation.ts]: @alee @Nick42791 removed the function and its invocations in the latest commit

**Comment by Nick42791** [comment]
@alee @lfaivre 
ok, so I finally just got a change to look closely at the pr and it appears that I was wrong.

first, we do need the function(well, a version of it)
it is still possible to type whatever number you want, which leaves us open to the user removing the number and not typing anything, which crashes the server immediately.

secondly, with the new way that the options are handled, putting them in their old spot, won't fix the problem. The solution is to make the makeTradeSafe function return the resources it changed. Once that's done, wrap the resourceAmounts in the trade package in TradeRequest.vue with the function. I'll see if I can't put up a pr doing this.

Sorry about the confusion!

**Comment by Nick42791** [comment]
@alee , I've put up an issue detailing the problem. The server crashes upon receiving the trade.
