### PR TITLE
fix: tutorial explains time remaining

### LINKED ISSUE #423: tutorial: phase timing should be described in relation to the ready button
The amount of time remaining in a phase needs to be ready at the same time as the ready button is mentioned

### PR DESCRIPTION
**Pull request by Nick42791**
should close #423

### CODE REVIEW

File: client/src/api/tutorial/steps/gamePlay.ts [hunk 1]
```diff
@@ -2,25 +2,47 @@ import { Step, LEFT } from '@port-of-mars/client/types/tutorial';
 import { CURATOR } from '@port-of-mars/shared/types';
 
 const steps: Array<Step> = [
+  {
+    target: '.tour-game-status',
```
Comment (chrstngyn) [inline client/src/api/tutorial/steps/gamePlay.ts:6]: the tutorial isn't starting - I think you forgot to set this class attribute on an html element

Comment (Nick42791) [reply client/src/api/tutorial/steps/gamePlay.ts]: haha 😅 thanks!
