### PR TITLE
fix(log): prevent mars log from perpetually generating in defeat and victory phases

### LINKED ISSUE #405: bug: after game ends, mars log keeps spawning messages
mars log keeps generating log messages

### PR DESCRIPTION
**Pull request by chrstngyn**
`SET_TIME_REMAINING` was getting called infinitely in the `gameLoop` on the server because `gameLoop` tries to transition the phase when `timeRemaining <= 0`

on `Entered[Defeat, Victory]Phase`, `timeRemaining` is set to infinity to prevent the `gameLoop` from transitioning the phase and spawning infinite mars logs

close #405

### CODE REVIEW

File: client/src/components/root/ContainerDefeat.vue [hunk 1]
```diff
@@ -42,45 +49,42 @@
...
-  }
+    logTime(timestamp: number) {
+      return new Date(timestamp).toLocaleTimeString();
+    }
 
-  marsLogTime(timestamp: number) {
-    return new Date(timestamp).toLocaleTimeString();
-  }
+    logColor(log: MarsLogData) {
+      if (log.category == 'SYSTEM HEALTH: DECREASE') return {backgroundColor: 'var(--marslog-red)'};
```
Comment (alee) [inline client/src/components/root/ContainerDefeat.vue:72]: it might be good to refactor this to a dictionary that maps the `log.category` to the color. Then you can boil this down to `return { backgroundColor: logCategoryColor[log.category] }`

File: server/src/rooms/game/events/index.ts [hunk 2]
```diff
@@ -310,6 +310,7 @@ export class EnteredDefeatPhase extends GameEventWithData {
 
   apply(game: GameState): void {
     game.phase = Phase.defeat;
+    game.timeRemaining = 9999999;         // set timeRemaining = infinite to prevent phase transitioning after game is over
```
Comment (alee) [inline server/src/rooms/game/events/index.ts:313]: I see why this is happening but should we instead exit from the gameLoop entirely and dispose the room when the game is over and everything has been finalized / properly persisted? @cpritcha I seem to recall you had some commits to fix GameRoom disposal..

Comment (cpritcha) [reply server/src/rooms/game/events/index.ts]: in the gameLoop we now call disconnect immediately once the game phase is defeat or victory.
